### ISSUE TITLE
Last view frame is not proper..

### ISSUE THREAD

**Issue by cloudjanak** [rickytan/RTGridView#2]
![img_3539](https://cloud.githubusercontent.com/assets/7457258/5537241/24670684-8ac4-11e4-8cc2-69f17b6500e3.PNG)

**Comment by rickytan** [comment]
please use `VE` and try again ?

**Comment by cloudjanak** [comment]
same problem

**Comment by cloudjanak** [comment]
please give the solution

**Comment by rickytan** [comment]
In face Apple provide a even better solution for this, use `UICollectionView` instead

**Comment by cloudjanak** [comment]
but i have implemented this

**Comment by cloudjanak** [comment]
please provide solution for this

**Comment by rickytan** [comment]
It works fine with me.
![ios 2014 12 24 9 32 14](https://cloud.githubusercontent.com/assets/1250207/5548742/7575dde8-8bb4-11e4-929f-657a8d25291b.png)
